apiVersion: batch/v1
kind: Job
metadata:
  name: model-train-job
spec:
  template:
    metadata:
      name: model-train-job-pod
    spec:
      containers:
        - name: model-train
          image: model-train:default
          command: ["python"]
          args: ["main-train.py"]
          envFrom:
            - configMapRef:
                name: my-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: model-data
              mountPath: "/model"
      restartPolicy: Never
      volumes:
        - name: model-data
          hostPath:
            path: "/tmp"
  backoffLimit: 4

